---
pool:
  name: default
  vmImage: 'ubuntu-latest'

trigger:
  - main

steps:
  - task: Npm@1
    inputs:
      command: 'install'
    displayName: 'installing npm'
    
  - script: npm run build
    displayName: 'build run'